apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxysql.fullname" . }}
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
data:
  SLEEP_BEFORE_CONNECTION_CHECK: {{ .Values.sleep_before_connection_check | quote }}
  proxysql.cnf: |
    {{- tpl (.Files.Get "files/proxysql.cnf") . | nindent 4 }}
